# file = open("hello.txt", "w")
# file.write('Hello, world!Pythons official CSV documentation says that the CSV library allows programmers to say,write this data in the format preferred by Excel,' or 'read data from this file which was generated by Excel, without knowing the precise details of the CSV format used by Excel.')
# file.close()
with open("hello.txt") as f:
    for line in f:
        #do something with line
        print(line)